site_name: Документация Punklab - Завод
site_url: https://mydomain.org/

markdown_extensions:
  # Python Markdown
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  # Python Markdown Extensions
  pymdownx.betterem:
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  # pymdownx blocks
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    - example
    # Custom types
    - info
    - check
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True


theme:
  name: material
  language: ru
  logo: static/img/logo-panklab.svg
  favicon: static/img/favicon.jpeg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Переключиться на светлую тему
  - media: '(prefers-color-scheme: light)'
    scheme: punklab
    toggle:
      icon: material/lightbulb
      name: Переключиться на темную тему
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Переключиться на тему системы
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

nav:
- Punklab - Завод:
    - index.md
- Флоу разработки:
    - development_flow/index.md
    - development_flow/system_design.md
    - development_flow/development.md
    - development_flow/technical_documentation.md
    - development_flow/deploy.md
  - Гайды и руководства:
    - Фундаментальные знания:
      - guides/fundamental/solid.md
    - Технологии:
      - guides/technologies/makefile.md
  # - Команда:
  #     - team/index.md
extra_css:
- static/css/extra.css
